select 
CommunityDimKey
,PropID
,MgmtID
,ListingTypeID
,PropStatusID
,PropName
,Address1
,Address2
,PostalCode
,Latitude
,Longitude
,Convert(VARCHAR(24),CreateDate)  
,HSPSContractId
,HSPSCustomerId
,City
,State
,Phone
,Fax
,Email
,NumUnits
,ClientPropertyID
,ClientPeopleSoftID
,MultipleLeadTypeID
,Convert(VARCHAR(24),LastUpdated)   
,CreatedBy
,ModifiedBy
,FeedSource
,Convert(VARCHAR(24),Last_Updated_By_Datafeed) 
,ProductID
,IVRContactTypeID
,IvrDispLocal
,IvrWhisper
,AAHSAFlag
,ConfirmAllCalls
,Convert(VARCHAR(24),ModifiedDate) 
,ATT_TollFree
,MLGFlag 
,TFNAssignmentID
,SourceSystem
,SourceSystemType
,Convert(VARCHAR(24),EffectiveFrom) 
,Convert(VARCHAR(24),EffectiveTo) 
from edw.tblcommunitydim
where CommunityDimKey between 5001 and 10000