Select 
AgentDimKey
,IsNull(Convert(VARCHAR(24),OfficeDimKey),'Null')
,ROW_UID_MIN
,IsNull(AgentDataSourceID,'Null')
,AgentSourceAliasID
,OfficeDataSourceID
,OfficeSourceAliasID
,IsNull(Convert(VARCHAR(24),HLC),'Null')
,IsNull(Convert(VARCHAR(24),CLC),'Null')
,AgentID
,AgentName
,AgentAddress1
,AgentAddress2
,AgentCity
,AgentCounty
,AgentPostalCode
,AgentStateCode
,AgentStateName
,AgentStateRegion
,AgentCountryCode
,AgentCountryName
,AgentCountryRegion
,AgentPhoneNum
,AgentFaxNum
,AgentEmailAddress
,AgentWebAddress
,AgentAutoRoutingCode
,AgentAddressLatitude
,AgentAddressLongitude
,AgentPrimaryContactName
,AgentStatus
,AgentCurrentFlag
,Convert(VARCHAR(24),EffectiveFrom)
,Convert(VARCHAR(24),EffectiveTo)
,IsNull(HLCTier,'Null')
,IsNull(LegacyRealtorID,'Null')
,IsNull(LegacyCustID,'Null')
,IsNull(AgentCellPhone,'Null')
,IsNull(AgentSlogan,'Null')
,IsNull(AgentPhotoURL1,'Null')
,IsNull(AgentPhotoURL2,'Null')
,IsNull(AgentLinkedInURL,'Null')
,IsNull(AgentFacebookURL,'Null')
,IsNull(AgentTwitterURL,'Null')
,IsNull(Convert(VARCHAR(24),AgentSinceDate),'Null')
,IsNull(AgentBOB,'Null')
,IsNull(AgentBOBTeam,'Null')
,IsNull(AgentBOBCurrentManager,'Null')
,IsNull(AgentBOBCurrentOwner,'Null')
,IsNull(AgentMLSRestriction,'Null')
,IsNull(AgentDoNotContact,'Null')
,IsNull(AgentRosterEmailAddress,'Null')
,IsNull(AgentConsumerInquiryEmailAddress,'Null')
,IsNull(AgentCustomerEmailAddress,'Null')
,IsNull(AgentName_Uhura,'Null')
,IsNull(AgentEmail_Uhura,'Null')
,IsNull(AgentMobilePhone_Uhura,'Null')
,IsNull(AgentGenPhone_Uhura,'Null')
,IsNull(AgentFaxPhone_Uhura,'Null')
,IsNull(AgentTollFreePhone_Uhura,'Null')
,IsNull(AgentURL_Uhura,'Null')
,IsNull(AgentReasonCode,'Null')
,IsAgentsStateLicensedSet
,IsAgentsCountryLicensedSet
,IsAgentsMarketingAreaSet
,IsAgentsMarketingZipSet
,IsAgentsDesignationSet
,IsAgentsKeywordSet
,IsAgentsAboutMeSet
, IsAgentsFirstYearOfServiceSet
,AgentProfilePercentageCompleteness
,IsNull(Convert(VARCHAR(24),CreatedDate),'Null')
,IsNull(CreatedBy,'Null')
,IsNull(Convert(VARCHAR(24),ModifiedDate),'Null')
,IsNull(Modifiedby,'Null')
,IsNull(Convert(VARCHAR(24),TeamDimKey),'Null')
,IsNull(AgentNRDSID,'Null')
,IsNull(AgentTeamStatus,'Null')
,IsNull(Convert(VARCHAR(24),MPRMasterAgentID),'Null')
,MLSTFNOptInFlag
,IsNull(AgentFirstName,'Null')
,IsNull(AgentLastName,'Null')
,IsNull(AgentMiddleName,'Null')
,IsNull(AgentNickName,'Null')
,IsNull(AgentTitle,'Null')
,IsNull(AgentSuffix,'Null')
,CoShowReportingOptoutFlg 
,LatestFlag
,IsNull(NARMembershipID,'Null')
,IsNull(SalesForceAccountID,'Null')
from edw.tblAgentDim where agentdimkey between 10443871 and 10448871 order by 1