select 
MemberDimKey
,MemberAccountID
,DisplayName
,FirstName
,LastName
,Gender
,EmailAddress
,MemberType
,PostalCode
,RegistrationSourceChannel
,RegistrationStatus
,CancellationReason
,Convert(VARCHAR(24),ProfileCreateDateMST,120) 
,Convert(VARCHAR(24),ProfileUpdateDateMST,120) 
,FacebookID
,CASE WHEN HasFacebookIDFlag = 'True' THEN 1 ELSE 0 END  
,FacebookStatus
,ReferredBy
,InAreaSince
,InCurrentHomeSince
,Convert(VARCHAR(24),iphoneUserStartDate,120) 
,Convert(VARCHAR(24),iphoneLastLoginDate,120) 
,Convert(VARCHAR(24),UserTypeConversionDate,120) 
,Convert(VARCHAR(24),EffectiveFrom,120) 
,Convert(VARCHAR(24),EffectiveTo,120) 
,Convert(VARCHAR(24),CreatedDate,120) 
,CreatedBy
,Convert(VARCHAR(24),ModifiedDate,120) 
,Modifiedby
,SourceApplicationName
,Interests0
,Interests1
,Interests2
,Interests3
,Interests4
,Interests5
,Interests6
,Convert(VARCHAR(24),MemberProfileMoveDate,120)  
,CommunicationPreferencesForm0
,CommunicationPreferencesDeliveriesMethod00
,CommunicationPreferencesDeliveriesFrequency00
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesCreatedAt00,120)  
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesUpdatedAt00,120)  
,CommunicationPreferencesDeliveriesMethod01
,CommunicationPreferencesDeliveriesFrequency01
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesCreatedAt01,120) 
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesUpdatedAt01,120)  
,CommunicationPreferencesDeliveriesMethod02
,CommunicationPreferencesDeliveriesFrequency02
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesCreatedAt02,120)  
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesUpdatedAt02,120)  
,CommunicationPreferencesForm1
,CommunicationPreferencesDeliveriesMethod10
,CommunicationPreferencesDeliveriesFrequency10
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesCreatedAt10,120)  
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesUpdatedAt10,120)  
,CommunicationPreferencesDeliveriesMethod11
,CommunicationPreferencesDeliveriesFrequency11
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesCreatedAt11,120)  
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesUpdatedAt11,120)  
,CommunicationPreferencesDeliveriesMethod12
,CommunicationPreferencesDeliveriesFrequency12
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesCreatedAt12,120)
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesUpdatedAt12,120)
,CommunicationPreferencesForm2
,CommunicationPreferencesDeliveriesMethod20
,CommunicationPreferencesDeliveriesFrequency20
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesCreatedAt20,120)
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesUpdatedAt20,120)
,CommunicationPreferencesDeliveriesMethod21
,CommunicationPreferencesDeliveriesFrequency21
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesCreatedAt21,120)
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesUpdatedAt21,120)
,CommunicationPreferencesDeliveriesMethod22
,CommunicationPreferencesDeliveriesFrequency22
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesCreatedAt22,120)
,Convert(VARCHAR(24),CommunicationPreferencesDeliveriesUpdatedAt22,120)
from RegistrationDM.tblMemberDim
where MemberDimKey between 1 and 8916