SELECT 
topProducerContractDimKey
,OwnerId
,CustomerStatus
,BID
,FirstName
,LastName
,EmailAddress
,Address1
,City
,RegionCode
,CountryCode
,PostCode
,PhoneNumber
,CompanyName
,OwnsCRM
,Convert(VARCHAR(24),CRMStartDate) 
,Convert(VARCHAR(24),CRMClosureDate)
,OwnsMS
,Convert(VARCHAR(24),MSStartDate) 
,Convert(VARCHAR(24),MSClosureDate) 
,OwnsMB
,Convert(VARCHAR(24),MBStartDate) 
,Convert(VARCHAR(24),MBClosureDate) 
,OwnsTWS
,Convert(VARCHAR(24),TWSStartDate) 
,Convert(VARCHAR(24),TWSClosureDate) 
,OwnsIDX
,Convert(VARCHAR(24),IDXStartDate) 
,Convert(VARCHAR(24),IDXClosureDate) 
,OwnsBlog
,Convert(VARCHAR(24),BlogStartDate)
,Convert(VARCHAR(24),BlogClosureDate)
,MLSID
,MLSAlias
,RealtorTypeID
,SiebelAccountID
,MonthlyValue
,OwnsJLP
,Convert(VARCHAR(24),JLPStartDate)
,Convert(VARCHAR(24),JLPClosureDate)
,IsCanadian
,Convert(VARCHAR(24),InsertDate) 
,Convert(VARCHAR(24),UpdateDate) 
,ChangeCheck
,DeleteFlag
from edw.tblTopProducerContractDim
where topProducerContractDimKey between 1 and 5000